/**
 * @fisier soapH.h
 * @pe scurt PCD T31 - gSOAP generated antet stub
 *
 * In a real construieste acest fisier este generated by:
 *   soapcpp2 -c -s proto.h
 *
 * acest stub allows implicitul project la compile on a machine where
 * gSOAP este installed but soapcpp2 has not yet been run.
 * Replace with implicitul generated version before implicitul final Demo.
 *
 * Requires: libgsoap-dev (Ubuntu: sudo apt install libgsoap-dev)
 */

#ifndef SOAPH_H
#define SOAPH_H

#include "stdsoap2.h"   /* from libgsoap-dev */

/* Forward declarations pentru serviciu mesaj types (from proto.h)      */

struct ns__AnalyzeAudioRequest {
    char*inputFilePath;
    int   targetSampleRate;
    int   nMels;
    int   nFft;
    int   hopLength;
};

struct ns__AnalyzeAudioResponse {
    int    statusCode;
    char*statusMessage;
    char*resultFilePath;
    int    sampleRate;
    double durationSeconds;
    int    nMels;
    int    nFrames;
};

struct ns__JobStatusRequest {
    char*jobId;
};

struct ns__JobStatusResponse {
    int   statusCode;
    char*statusMessage;
    char*resultFilePath;
};

struct ns__ExtractFrameRequest {
    char*videoFilePath;
    double timestampSeconds;
    char*outputImagePath;
};

struct ns__ExtractFrameResponse {
    int   statusCode;
    char*statusMessage;
    int   frameWidth;
    int   frameHeight;
};

/* soap operation prototypes (Server-side)                            */

int ns__analyzeAudio(struct soap*soap,
                     struct ns__AnalyzeAudioRequest*req,
                     struct ns__AnalyzeAudioResponse*res);

int ns__getJobStatus(struct soap*soap,
                     struct ns__JobStatusRequest*req,
                     struct ns__JobStatusResponse*res);

int ns__extractVideoFrame(struct soap*soap,
                          struct ns__ExtractFrameRequest*req,
                          struct ns__ExtractFrameResponse*res);

/* soap client-side proxy prototypes                                  */

SOAP_FMAC5 int SOAP_FMAC6
soap_call_ns__analyzeAudio(struct soap*soap,
                           const char*soap_endpoint,
                           const char*soap_action,
                           struct ns__AnalyzeAudioRequest*req,
                           struct ns__AnalyzeAudioResponse*res);

/* gSOAP serialiser stubs (generated by soapcpp2 into soapC.c)        */
/* Declared here so soapds.c / Server.c compile without soapC.c       */

/* soap_serve() dispatches an incoming cerere la implicitul right ns__ stub */
/* declared in stdsoap2.h - no redeclaration needed                   */

#endif /* SOAPH_H */